### ISSUE TITLE
No Error Handling

### ISSUE THREAD

**Issue by KRollenbeck** [neckaros/rs_torrent_magnet#1]
For some of my Torrents it can't generatte a magnet link. But I can't skip them cause the program panics at the decode() function and there is no Error handling.

**Comment by neckaros** [comment]
Can you post the torrent file somewhere so I can have a look?

In the meantime I will add error handling

**Comment by neckaros** [comment]
Error management avaiable on Crates.io from version 0.3
[commit #b8b7228ffd6f15ef427fc561b55bfddafdb13cb5](https://github.com/neckaros/rs_torrent_magnet/commit/b8b7228ffd6f15ef427fc561b55bfddafdb13cb5)

**Comment by KRollenbeck** [comment]
> Can you post the torrent file somewhere so I can have a look?
> 
> In the meantime I will add error handling

https://trbt.cc/91jxb20v34y6.html

I hope the link works. I couldn't upload the torrent directly.

And thank you much for helping :).

**Comment by neckaros** [comment]
I have added error handling so i will close this issue.
I could not download the torrent file from the link. If it is working on a website like https://nutbread.github.io/t2m/ please open a new issue
